spring:
  datasource:
    url: jdbc:h2:file:./data/streetdicodb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false
  liquibase:
    changeLog: classpath:db/changelog/changelog-master.yml

  #security: enabled=false




