name: STEETDICO BACK DEV
run-name: Deploy to streetdico dev by @${{ github.actor }}

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    environment: dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github 
          settings-path: ${{ github.workspace }} 

      - name: Delete build folder
        run: rm -rf target/

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload artefact
        uses: actions/upload-artifact@v3
        with:
          name: streetdico-back-dev
          path: ./target
      
# Deploy on dev
  deployment:
    environment: dev
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download artefact
        uses: actions/download-artifact@v2.1.1
        with:
            name: streetdico-back-dev
            path: ./target
                    
      - name: Copy run executable
        run: scp ${{ secrets.KEY_PAIR_SECRET }} ./run_jar.sh ec2-user@:${{ env.INSTANCE_DNS }}/home/ec2-user

      - name: Copy artefact 
        run: scp ${{ secrets.KEY_PAIR_SECRET  }} ./target/${{ env.TARGET_NAME}} ec2-user@:${{ env.INSTANCE_DNS }}/home/ec2-user

      - name: Connect to ec2 and run jar
        run: ssh ${{ secrets.KEY_PAIR_SECRET  }} ec2-user@${{ env.INSTANCE_DNS }} ./run_jar.sh

 
        
      

